Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np. 

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. 
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [56]:
import numpy as np

In [57]:
# Создаем 2-ух мерную матрицу
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7],])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [58]:
# Вычисляем среднее значение по каждому столбцу
mean_a = a.mean(axis = 0)
print(mean_a)

[2.  8.4]


Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [59]:
# Воспользуемся функцией для вычитания вида:
# c = a - b
# c = np.subtract(a, b)
a_centered = np.subtract(a, mean_a)
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [60]:
# Вытащим в отдельные вектора a & b из двумерного массива a_centered
a1 = a_centered[:,0]
b1 = a_centered[:,1]
print(a1)
print(b1)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]


In [61]:
# Найдем скалярное произведение векторов
a_centered_sp = np.dot(a1,b1)
print(a_centered_sp)

8.0


In [62]:
# Найдем число наблюдений используя атрибут shape
N = a_centered.shape[0]
print(N)

5


In [63]:
# Найдем частное от a_centered_sp на N-1
quotient = a_centered_sp / (N - 1)
print(quotient)

2.0


Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [64]:
# Транспонируем матрицу a
at = np.transpose(a)
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [65]:
# найдем ковариацию с помощью функции np.cov
cov = np.cov(at)
print(cov)

[[1.  2. ]
 [2.  4.3]]


In [66]:
# Запишем коротко и найдем искомое значение ковариации в строке 0 и столбце 1 
cov = np.cov(a.transpose())[0,1]
print(cov)

2.0
